### PR TITLE
add extension 'sidebar-sections'

### PR DESCRIPTION
**Pull request by EliWimmer**
**Which bug report or feature request do these changes address?**
n/a

**What does your code do and why?**
Creates margin and optional headers above up to 4 (arbitrary) user chosen pages, allows user to choose between 3 margin sizes, and the option to disable the native 'private' header.

Margins are made by a classList.add to matching data-block-id's in the sidebar. Headers (if provided) use web.html/web.render to insert them and are styled to match the native headers. Private header is hidden by adding a class to the element.

All operations wait for element load (web.whenReady) and are conditional and will not run if user input is invalid, or in the case of private header, if no private header exists (IE nothing favorited & nothing shared).

### CODE REVIEW

**Comment by EliWimmer** [comment]
Image in action with 4 sections, two of which with headers:
image

**Comment by dragonwocky** [comment]
This looks great!

v0.11.1 will focus on bug fixes, this will be part of v0.12.0. There are a few parts of the code that could be cleaned up a bit and there may be a better way to structure the options to allow for an "unlimited" number of sections, but I can do those bits.

**Comment by EliWimmer** [comment]
Missed this comment! Sounds good. My strengths are definitely design not programming so I do apologize for any poor practices.

**Comment by dragonwocky** [comment]
Hey @EliWimmer, sorry for such a long wait. I'm getting the ball rolling for release now and the notion-enhancer has returned to a monorepo architecture for simplification of development & contributions, so I'm archiving this repository. If you're still keen on building this extension for the notion-enhancer, feel free to open a PR over at https://github.com/notion-enhancer/notion-enhancer. I'd love to include it, so I'm very happy to do the work of porting it across (and supporting additional/unlimited user-defined sidebar sections), but if you open the PR then the git blame will point to you as the extension's author. Thanks!

**Pull request closed without merging**
